version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    # depends_on:
    #   - Logstash
    #   - Kibana
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  # elasticsearch:
  #   image: elasticsearch:8.3.3
  #   container_name: elasticsearch
  #   restart: always
  #   volumes:
  #   - elastic_data:/logstash/elasticsearch/data/
  #   environment:
  #     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  #     discovery.type: single-node    
  #   ports:
  #   - '9200:9200'
  #   - '9300:9300'
  #   networks:
  #     - elk

  # Logstash:
  #   image: logstash:7.16.2
  #   container_name: logstash
  #   restart: always
  #   volumes:
  #   - ./logstash/:/logstash_dir
  #   command: logstash -f /logstash/logstash.conf 
  #   depends_on:
  #     - Elasticsearch
  #   ports:
  #   - '9600:9600'
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
  #   networks:
  #     - elk

  # Kibana:
  #   image: kibana:7.16.2
  #   container_name: kibana
  #   restart: always       
  #   ports:
  #   - '5601:5601'
  #   environment:
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200  
  #   depends_on:
  #     - Elasticsearch  
  #   networks:
  #     - elk

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  # elastic_data: {}

# networks:
#   elk: